# Generated by Django 5.2.17 on 2026-09-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chamado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('categoria', models.CharField(choices=[('hardware', 'Computador não liga/Computador lento'), ('software', 'Programa não funciona'), ('redes', 'Problemas com internet/sistema'), ('nao_identificada', 'Não sei identificar')], max_length=20)),
                ('data_inicio', models.DateField()),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('pendente', 'Aguardando triagem'), ('confirmado', 'Em atendimento'), ('cancelado', 'Cancelado')], default='pendente', max_length=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
